[default.extend-words]
contextful = "contextful"
MacOS = "macOS"

[default.extend-identifiers]
ba = "ba"
Flate = "Flate"
"Haß" = "Haß"
wrk = "wrk"
SEH = "SEH"
Packt = "Packt"

[default]
extend-ignore-re = [
  "Ingenius System Manager",
  "Ruby-ists",
  "ruby-ists",
  "Nikola TRE",
  "Ryan Worl",
]

[files]
extend-exclude = [
  "_sass/components/_highlight.scss",
  "/_site*/",
  "**/crystal-pgp-key.txt", "gemset.nix",
  "_style_guide/typography/footnotes.md",
]
